import { ProblemType } from './types';

export const THEMES: Record<ProblemType, string[]> = {
    Integration: [
        'Indefinite Integrals of Polynomials',
        'Definite Integrals',
        'Area Under a Curve',
        'Area Between Two Curves',
        'Integration by Substitution (u-sub)',
        'Integration by Parts',
        'Integration Using Partial Fractions',
        'Integration of Trigonometric Functions',
        'Integration of Exponentials',
        'Integration of Logarithmic Functions',
        'Integration Using Trigonometric Identities',
        'Integration Using Completing the Square',
        'Integration of Rational Functions',
        'Improper Integrals',
        'Change of Limits in Definite Integrals',
        'Volumes of Revolution (x-axis)',
        'Volumes of Revolution (y-axis)',
        'Volumes Using Cylindrical Shells',
        'Arc Length of a Curve',
        'Surface Area of Revolution',
        'Average Value of a Function',
        'Trapezium Rule',
        'Midpoint Rule',
        "Simpson's Rule",
        'Error Bounds for Numerical Integration',
        'First-Order Differential Equations',
        'Separable Differential Equations',
        'Differential Equations with Initial Conditions',
        'Growth and Decay Models',
        'Logistic Growth',
        'Integration of Hyperbolic Functions',
        'Reduction Formulae',
        'Integration Using Recurrence Relations',
        'Integration Involving Absolute Values',
        'Integration of Piecewise Functions',
        'Parametric Integration',
        'Integration in Polar Coordinates',
        'Work Done by a Force',
        'Centre of Mass (1D)',
        'Probability Density Functions',
        'Expectation Using Integration',
        'Integration by Comparison',
        'Integration of Inverse Trig Functions',
        'Change of Variable in Integrals',
        'Applications to Kinematics',
        'Applications to Economics',
        'Applications to Physics',
        'Mixed Integration Techniques',
        'Proofs Using Integration',
    ],
    Differentiation: [
        'First Principles of Differentiation',
        'Power Rule',
        'Constant Multiple Rule',
        'Sum and Difference Rule',
        'Product Rule',
        'Quotient Rule',
        'Chain Rule',
        'Implicit Differentiation',
        'Parametric Differentiation',
        'Differentiation of Trigonometric Functions',
        'Differentiation of Inverse Trig Functions',
        'Differentiation of Exponential Functions',
        'Differentiation of Logarithmic Functions',
        'Differentiation of Composite Functions',
        'Second Derivatives',
        'Higher-Order Derivatives',
        'Stationary Points',
        'Local Maxima and Minima',
        'Points of Inflection',
        'Concavity and Curve Sketching',
        'Tangents to Curves',
        'Normals to Curves',
        'Rates of Change',
        'Connected Rates',
        'Kinematics Applications',
        'Optimization Problems',
        'Related Rates in Geometry',
        'Differentiation of Hyperbolic Functions',
        'Logarithmic Differentiation',
        'Differentiation of Piecewise Functions',
        'Differentiation of Absolute Value Functions',
        'Small Increments and Approximations',
        'Linearization',
        'Newton-Raphson Method',
        'Error Estimation',
        'Differentiation of Parametric Curves',
        'Differentiation in Polar Coordinates',
        'Velocity and Acceleration',
        'Motion with Variable Acceleration',
        'Differentiation Using Series',
        'Differentiation of Inverse Functions',
        'Proofs Using Differentiation',
        'Monotonicity of Functions',
        'Asymptotic Behaviour',
        'Curve Intersections',
        'Applications to Economics',
        'Applications to Physics',
        'Mixed Differentiation Techniques',
    ],
    Limits: [
        'Limits at a Point',
        'One-Sided Limits',
        'Limits at Infinity',
        'Infinite Limits',
        "L'Hopital's Rule",
        'Squeeze Theorem',
        'Limits of Rational Functions',
        'Limits of Trigonometric Functions',
        'Limits of Exponential Functions',
        'Limits of Logarithmic Functions',
        'Continuity and Limits',
        'Removable Discontinuities',
        'Jump Discontinuities',
        'Asymptotic Limits',
        'Limits of Sequences',
        'Limits Involving Absolute Values',
        'Indeterminate Forms',
        'Delta-Epsilon Definition',
        'Limits of Composite Functions',
        'Limits in Polar Coordinates',
    ],
};
