import { ProblemType } from './types';

export const THEMES: Record<ProblemType, string[]> = {
    Integration: [
        'Indefinite Integrals of Polynomials',
        'Definite Integrals',
        'Area Under a Curve',
        'Area Between Two Curves',
        'Integration by Substitution (u-sub)',
        'Integration by Parts',
        'Integration Using Partial Fractions',
        'Integration of Trigonometric Functions',
        'Integration of Exponentials',
        'Integration of Logarithmic Functions',
        'Integration Using Trigonometric Identities',
        'Integration Using Completing the Square',
        'Integration of Rational Functions',
        'Improper Integrals',
        'Change of Limits in Definite Integrals',
        'Volumes of Revolution (x-axis)',
        'Volumes of Revolution (y-axis)',
        'Volumes Using Cylindrical Shells',
        'Arc Length of a Curve',
        'Surface Area of Revolution',
        'Average Value of a Function',
        'Trapezium Rule',
        'Midpoint Rule',
        'Simpson’s Rule',
        'Error Bounds for Numerical Integration',
        'First-Order Differential Equations',
        'Separable Differential Equations',
        'Differential Equations with Initial Conditions',
        'Growth and Decay Models',
        'Logistic Growth',
        'Integration of Hyperbolic Functions',
        'Reduction Formulae',
        'Integration Using Recurrence Relations',
        'Integration Involving Absolute Values',
        'Integration of Piecewise Functions',
        'Parametric Integration',
        'Integration in Polar Coordinates',
        'Work Done by a Force',
        'Centre of Mass (1D)',
        'Probability Density Functions',
        'Expectation Using Integration',
        'Integration by Comparison',
        'Integration of Inverse Trig Functions',
        'Change of Variable in Integrals',
        'Applications to Kinematics',
        'Applications to Economics',
        'Applications to Physics',
        'Mixed Integration Techniques',
        'Proofs Using Integration',
    ],

    Differentiation: [
        'First Principles of Differentiation',
        'Power Rule',
        'Constant Multiple Rule',
        'Sum and Difference Rule',
        'Product Rule',
        'Quotient Rule',
        'Chain Rule',
        'Implicit Differentiation',
        'Parametric Differentiation',
        'Differentiation of Trigonometric Functions',
        'Differentiation of Inverse Trig Functions',
        'Differentiation of Exponential Functions',
        'Differentiation of Logarithmic Functions',
        'Differentiation of Composite Functions',
        'Second Derivatives',
        'Higher-Order Derivatives',
        'Stationary Points',
        'Local Maxima and Minima',
        'Points of Inflection',
        'Concavity and Curve Sketching',
        'Tangents to Curves',
        'Normals to Curves',
        'Rates of Change',
        'Connected Rates',
        'Kinematics Applications',
        'Optimization Problems',
        'Related Rates in Geometry',
        'Differentiation of Hyperbolic Functions',
        'Logarithmic Differentiation',
        'Differentiation of Piecewise Functions',
        'Differentiation of Absolute Value Functions',
        'Small Increments and Approximations',
        'Linearization',
        'Newton–Raphson Method',
        'Error Estimation',
        'Differentiation of Parametric Curves',
        'Differentiation in Polar Coordinates',
        'Velocity and Acceleration',
        'Motion with Variable Acceleration',
        'Differentiation Using Series',
        'Differentiation of Inverse Functions',
        'Proofs Using Differentiation',
        'Monotonicity of Functions',
        'Asymptotic Behaviour',
        'Curve Intersections',
        'Applications to Economics',
        'Applications to Physics',
        'Mixed Differentiation Techniques',
    ],

    'Mathematics (9709)': [
        'Algebraic Manipulation',
        'Surds and Indices',
        'Quadratic Functions',
        'Completing the Square',
        'Discriminant and Roots',
        'Inequalities',
        'Simultaneous Equations',
        'Functions and Notation',
        'Composite Functions',
        'Inverse Functions',
        'Domain and Range',
        'Graphs of Functions',
        'Transformations of Graphs',
        'Coordinate Geometry of Lines',
        'Coordinate Geometry of Circles',
        'Intersection of Curves',
        'Trigonometric Ratios',
        'Trigonometric Identities',
        'Trigonometric Equations',
        'Radian Measure',
        'Arc Length',
        'Sector Area',
        'Sequences',
        'Arithmetic Progressions',
        'Geometric Progressions',
        'Sum to Infinity',
        'Binomial Expansion (Positive Integer)',
        'Binomial Expansion (Fractional Index)',
        'Vectors in 2D',
        'Vectors in 3D',
        'Scalar Product',
        'Differentiation Basics',
        'Applications of Differentiation',
        'Integration Basics',
        'Applications of Integration',
        'Numerical Methods',
        'Trapezium Rule',
        'Kinematics in 1D',
        'Displacement, Velocity, Acceleration',
        'Motion Under Constant Acceleration',
        'Forces and Newton’s Laws',
        'Equilibrium of Forces',
        'Momentum and Impulse',
        'Work, Energy and Power',
        'Connected Particles',
        'Projectiles',
        'Mathematical Modelling',
        'Problem Solving Techniques',
        'Proof and Reasoning',
    ],

    'Further Math (9231)': [
        'Complex Numbers (Basic Operations)',
        'Argand Diagrams',
        'Modulus and Argument',
        'De Moivre’s Theorem',
        'Roots of Complex Numbers',
        'Loci in the Complex Plane',
        'Polynomials and Roots',
        'Relations Between Roots and Coefficients',
        'Matrices',
        'Matrix Multiplication',
        'Inverse Matrices',
        'Determinants',
        'Linear Transformations',
        'Eigenvalues and Eigenvectors',
        'Systems of Linear Equations',
        'Polar Coordinates',
        'Polar Curves',
        'Summation Notation',
        'Sigma Algebra',
        'Convergence of Series',
        'Maclaurin Series',
        'Taylor Series',
        'Differential Equations (First Order)',
        'Second-Order Differential Equations',
        'Auxiliary Equation Method',
        'Particular Integrals',
        'Homogeneous Differential Equations',
        'Vectors in 3D',
        'Vector Product (Cross Product)',
        'Scalar Triple Product',
        'Lines in 3D',
        'Planes in 3D',
        'Angle Between Lines and Planes',
        'Shortest Distance Problems',
        'Hyperbolic Functions',
        'Identities of Hyperbolic Functions',
        'Inverse Hyperbolic Functions',
        'Mathematical Induction',
        'Proof by Contradiction',
        'Recurrence Relations',
        'Inequalities (AM-GM, Cauchy-Schwarz)',
        'Advanced Curve Sketching',
        'Asymptotes and Limits',
        'Further Integration Techniques',
        'Further Differentiation Techniques',
        'Applications to Mechanics',
        'Applications to Physics',
        'Advanced Problem Solving',
    ],
};
